/* Copyright (C) 2022-present Jube Holdings Limited.
 *
 * This file is part of Jube™ software.
 *
 * Jube™ is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License
 * as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * Jube™ is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.

 * You should have received a copy of the GNU Affero General Public License along with Jube™. If not,
 * see <https://www.gnu.org/licenses/>.
 */

using System.ComponentModel;

// ReSharper disable NotAccessedPositionalProperty.Global

namespace Jube.Dto.PostgresStatementStatistics
{
    public sealed record PostgresStatementStatisticsDto(
        [property:
            Description(
                "pg_stat_statements' own hash identifying this normalised query shape -- the same query text with different literal values shares one QueryId. Identifies a shape, not a quantity, so it is excluded from this DTO's summary Statistics despite being numeric.")]
        long QueryId,
        [property: Description("Database this query shape was executed against.")]
        string? DatabaseName,
        [property: Description("Role name that executed this query shape.")]
        string? UserName,
        [property:
            Description(
                "The normalised query text -- literal values replaced with $1, $2, etc, so many calls with different literals collapse into one row. Visible here to the same extent Postgres' own role-based visibility rules allow for the role this connection authenticates as -- a non-superuser role without pg_read_all_stats only ever sees its own queries in full.")]
        string? Query,
        [property:
            Description(
                "Number of times this query shape has been executed, accumulated since the extension was created or last reset.")]
        long Calls,
        [property: Description("Total rows retrieved or affected across every call.")]
        long Rows,
        [property: Description("Total time spent executing this query shape, summed across every call.")]
        double TotalExecTimeMilliseconds,
        [property:
            Description(
                "TotalExecTimeMilliseconds / Calls -- the headline 'how expensive is this query on average' figure.")]
        double MeanExecTimeMilliseconds,
        double MinExecTimeMilliseconds,
        double MaxExecTimeMilliseconds,
        [property:
            Description(
                "Standard deviation of execution time across calls -- a large value alongside a low MeanExecTimeMilliseconds means this query shape is usually cheap but occasionally very expensive (a classic sign of a plan that only sometimes picks a bad index, or contention that only sometimes bites), which the mean alone hides.")]
        double StddevExecTimeMilliseconds,
        [property:
            Description(
                "Shared buffer bytes served from cache across every call. Compare against SharedBlksReadBytes for this query shape's cache-hit ratio -- a low ratio for a frequently-run query is a strong 'needs an index, or shared_buffers is too small' signal.")]
        long SharedBlksHitBytes,
        [property: Description("Shared buffer bytes read from disk (not served from cache) across every call.")]
        long SharedBlksReadBytes,
        [property:
            Description(
                "Bytes read back from temporary files across every call -- the read side of a sort or hash that spilled to disk because it did not fit in work_mem. See TempBlksWrittenBytes for the write side; non-zero here for a hot query is a direct 'raise work_mem, or fix the query' signal.")]
        long TempBlksReadBytes,
        [property:
            Description(
                "Bytes written to temporary files across every call -- the write side of the same spill-to-disk described on TempBlksReadBytes.")]
        long TempBlksWrittenBytes,
        [property:
            Description(
                "WAL bytes generated by this query shape across every call -- a heavy-write query shape's actual replication/archiving cost.")]
        long WalBytes);
}